"""added list_id foreign key to card model

Revision ID: 4517b3940f61
Revises: 133a38654ac6
Create Date: 2021-12-17 16:14:56.254359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4517b3940f61'
down_revision = '133a38654ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cards', 'lists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'list_id')
    # ### end Alembic commands ###
