"""empty message

Revision ID: ff46dfe3dd16
Revises: 15d989b0f7d5
Create Date: 2022-01-24 18:16:38.055883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff46dfe3dd16'
down_revision = '15d989b0f7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('list_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'list_order')
    # ### end Alembic commands ###
