"""empty message

Revision ID: d7b591abe3a2
Revises: ff46dfe3dd16
Create Date: 2022-01-24 18:58:55.090779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b591abe3a2'
down_revision = 'ff46dfe3dd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'list_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'list_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
